### ISSUE TITLE
Tiering rule needs to support adding access time for registration

### ISSUE THREAD

**Issue by masilamani** [irods/irods_capability_tiered_storage#18] opened 2018-03-19 19:14 UTC
The tiering rule needs to support adding access time for registration, not just put.   Currently, when the file is ingested using ireg command.  Example:  

ireg -R fastResc /tmp/foo.txt /TestZone/home/rods/foo.txt
imeta ls -d /TestZone/home/rods/foo.txt

The "irods::access_time" AVU metadata is not added automatically by the tiered storage framework and that's why it is triggering t move the data between tiers in the tier group based on the tier policy time-based constraint.

As a workaround, i have added below code in the rule base to add "irods::access_time" AVU metadata.

get_access_time_attribute(*attr) {
    *attr = "irods::access_time"
}

update_access_time_for_data_object(*objPath) {
    # the system time is reported in seconds
    *err = errormsg(msiGetSystemTime(*time, ""), *msg)
    if(0 != *err) {
        writeLine("serverLog", "msiGetSystemTime :: [*err] [*msg]")
    }

    # wash the time through an int to fix formatting
    *time_int = int(*time)
    *time_str = str(*time_int)

    # the attribute representing the access time is abstracted into a
    # configuration rule base to keep concerns separated
    get_access_time_attribute(*atime_attr)

    writeLine("serverLog", "set AVU metdata *atime_attr => *time_str for object path *objPath");
    msiAddKeyVal(*Keyval, "*atime_attr", "*time_str");
    msiSetKeyValuePairsToObj(*Keyval, "*objPath","-d");
}
acPostProcForFilePathReg {

    if ($rescName == 'fastResc') {
        update_access_time_for_data_object($objPath);
    }

}

**Comment by jasoncoposky** [comment] 2018-03-22 00:25
closing as duplicate of #9

**Closed by jasoncoposky** 2018-03-22 00:25 UTC
